# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:

- task: CmdLine@2
  name: 'install_firebase_admin'
  inputs:
    script: |
      echo '--------------------------------------------------------'
      echo 'Installing Firebase-Admin'
      echo '--------------------------------------------------------'
      npm install firebase-admin
      echo 'Firebase-Admin install completed.'
      
- task: CmdLine@2
  name: 'publish_remote_config_to_test'
  inputs:
    script: |
      echo '--------------------------------------------------------'
      echo "Updating remote config of test-biletdukkani"
      echo '--------------------------------------------------------'
      node index.js update test

      #if 'node index.js update test' is used, uncomment these lines
      #echo '--------------------------------------------------------'
      #echo "Cleaninig local config template of test-biletdukkani"
      #echo '--------------------------------------------------------'
      #rm config.json


- task: CmdLine@2
  name: 'publish_remote_config_to_staging'
  inputs:
    script: |
      echo '--------------------------------------------------------'
      echo "Updating remote config of staging-biletdukkani"
      echo '--------------------------------------------------------'
      node index.js update staging

      #if 'node index.js update test' is used, uncomment these lines
      #echo '--------------------------------------------------------'
      #echo "Cleaninig local config template of staging-biletdukkani"
      #echo '--------------------------------------------------------'
      #rm config.json


- task: CmdLine@2
  name: 'publish_remote_config_to_prod'
  inputs:
    script: |
      echo '--------------------------------------------------------'
      echo "Updating remote config of prod-biletdukkani"
      echo '--------------------------------------------------------'
      node index.js update prod